<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [ ]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"}

#wait i just copy pasted but this section doesn't rly have a question to work on 

### 1.2 Accessing data from a list (or array)

In [10]:
#fetching data from lists

py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

index = int(input("Which number would you like?"))

print (py_super_names[index])

#i p much just always try to put input coz i hate changing my code

Which number would you like?0
Black Widow


In [25]:
#learnt the eval string 
#trying to make it such that the user can customise the list and index they want 

First = py_super_names
Second = py_real_names

storage_area = eval(input("Which list would you like to fetch data from?").capitalize())
index = eval(input("Which number would you like?"))

print (storage_area[index])

#eval is p neat

Which list would you like to fetch data from?first
Which number would you like?0
Black Widow


### 1.3 Accessing data from a dictionary

In [32]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                   "Iron Man": "Tony Stark",
                  "Doctor Strange": "Stephen Strange"}

def reveal_identity(name):
    print(superhero_info[name.title()])
    
name = input("Who would you like to expose?")

reveal_identity(name)



Who would you like to expose?iron man
Tony Stark


In [ ]:
#so far have learnt: eval, title, capitalise

### 1.4 Higher dimensional lists

In [ ]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

#wait so an array is just multiple dictionaries or lists grouped together?

## 2 Lists vs. Arrays

### 2.1 Size

In [3]:
#checking number of elements in the array (or a list in this case)
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

import numpy as np 
np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

        #gotta first equate the initial list to the array
        
len(np_array_2d)

10

In [5]:
#alternative method of checking the number of elements AND shape of the array (which is also just a list in this case)

py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"], [11, "K"], [12, "L"]]

import numpy as np 
np_array_2d = np.array(py_list_2d)

#gotta first equate the initial list to the array

np_array_2d.shape

#wait how do i get it to be a 3 instead of a 2 in my output 
#does the 2 mean like 2d?

(12, 2)

### 2.2 Arrays are fussy about type

In [6]:
py_list = [1, 1.5, 'A']
np.array(py_list)

#lowkey dk what's gg on here
#they said observe how the numbers get changed to english
#isit coz they now have quotations marks which is why technically it's considered as text/english?

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [7]:
#arrays can add number but lists cannot 

py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array
#just quote the array and add 10
#now gonna test using a list which won't work 

py_list + 10 

#output says can combine list with list but not int with list

TypeError: can only concatenate list (not "int") to list

In [4]:
#gonna create a new dummy list and try to combine
#expecting to need to have the same numbering format before i can combine the lists but we'll see ig 

import numpy as np

py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)       

#dummy list 

py_dummy = [1,1,1,1,1]
np_array = np.array(py_dummy)

py_list + py_dummy 

[1, 2, 3, 4, 5, 1, 1, 1, 1, 1]

### 2.4 Adding another list

In [5]:
#doing without referring

#gotta list in terms of py first
py_list_1=[2,2,2,2,2]
py_list_2=[5,5,5,5,5]

#gotta convert from list to array
np_array=np.array(py_list_1)
np_array=np.array(py_list_2)

#now ig i can just add the 2 reformed lists together
py_list_1 + py_list_2


[2, 2, 2, 2, 2, 5, 5, 5, 5, 5]

### 2.5 Multiplying by a Number

In [6]:
#mutiplying a list 

py_list= [1,2,3,4,5]

py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [7]:
#multiplying an array 

py_list= [1,2,3,4,5]

np_array= np.array(py_list)

py_list*2

#fail

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

Wait looking at part 2.4 shouldnt my com know that list is now an array 
Why doesnt my attempt work 

In [8]:
#multiplying an array part 2

py_list= [1,2,3,4,5]

np_array= np.array(py_list)

np_array*2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [9]:
#squaring an array 
#just changing the operator here

py_list= [1,2,3,4,5]

np_array= np.array(py_list)

np_array**2

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [10]:
#use list to check if the list only contains one value and is equal to the value i type in?
#does not work for more or less than only the equal operator

py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

py_list == 3

False

In [12]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)       

py_list == 1

False

In [14]:
#to check for each input within the list 
#need to convert to array first 

py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)       

np_array == 1


array([ True, False, False, False, False])

### 2.8 Mathematics

In [15]:
#sum max min PREfix works for list embedded within brackets 
#mean prefix does not work for py_list 

#sum mean max min SUFfix can only be done for arrays

py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)    

sum(py_list)

15

In [16]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list) 

np_array.mean()

3.0

In [17]:
#incorrect scenarios box for testing
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list) 

mean(py_list)

NameError: name 'mean' is not defined

## Exercise 1 :  Total recall?

Similarities:
1. Both lists and arrays have the same index where the left hand side starts of as number 0 
2. Conditions can be checked against both lists and arrays

Differences:
1. Mathematical operator are applied onto the individual terms themselves in arrays but only for the whole quantity of elements within lists.
2. Arrays can provide further details (e.g. mean) on  the elements compared to lists which only state the max, min and sum.


## Exercise 2 :  Index me

In [19]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0]) # Prints 'a1'
print(py_list[2]) # Prints 'c3'
print(py_list[4]) # Prints 'e5'
print(py_list[6]) # Prints 'g7'
print(py_list[8]) # Prints 'i9'

a1
c3
e5
g7
i9


In [45]:
#p sure there's a better way 
#is there a way to make code that detects the number inside

py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]

np_array = np.array(py_list)

indexing_things = np_array % 2 == 0

if np_array % 2 == 0:
    print(np_array)


TypeError: ufunc 'remainder' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [50]:
import numpy as np 

py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]

np_array = np.array(py_list)
    
if np_array % 2 == 0:
    print(np_array)



TypeError: ufunc 'remainder' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

## Exercise 3 :  Capitalise Heros

In [53]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

name = input("Who would you like to capitalise?").title()

print(f'{superhero_info[name].upper()}')

Who would you like to capitalise?tony stark
IRON MAN


## Exercise 4 :  How many ones

In [17]:
import numpy as np 

numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]            

numpy_numbers = np.array(numbers) == 1

print((numpy_numbers == 1).sum())

9
