<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [6]:
import numpy as np
py_list=["a1", "b2", "c3", "d4", "e5","f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

x = np_array

x[0:10:2]

#use the double colon for skipping over a range of terms in an array

array(['a1', 'c3', 'e5', 'g7', 'i9'], dtype='<U3')

### 1.2 Subsetting by masking (Arrays only)

In [17]:
#u need an array on the elements which meet condition
import numpy as np

py_list=[1,2,3,4,5,6]
np_array=np.array(py_list)

mask = np_array % 2 == 0

np_array[mask]

array([2, 4, 6])

In [15]:
#list is used to check true false
import numpy as np

py_list=[1,2,3,4,5,6]
np_array=np.array(py_list)

mask = np_array > 3

print(mask)

[False False False  True  True  True]


### 1.3 Indexing & Slicing 2D Lists

In [20]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

py_list_2d[9][1]

'J'

In [3]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

py_list_2d[3:][3]

[7, 'G']

In [6]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

py_list_2d[0:8:2]

[[1, 'A'], [3, 'C'], [5, 'E'], [7, 'G']]

### 1.4 Indexing & Slicing 2D Arrays

In [11]:
#using an array to call instead of a list

import numpy as np 

np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

np_array_2d[9,1]

'J'

In [10]:
import numpy as np 

np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

np_array_2d[3:6, 0]

#the range and the specific value are only separated by a comma in arrays

array(['4', '5', '6'], dtype='<U11')

### 1.5 Growing lists

In [29]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [30]:
x=[1]
x+= [2, 3, 4]
x

#just insert the new elements at one shot 
#can use += instead of x = x + whatever

[1, 2, 3, 4]

In [12]:
x=[1]
x= [2, 3, 4] + x
x

#dictate the position of x on RHS if not adding new terms to the back 

[2, 3, 4, 1]

In [ ]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

#dont need to type print for jupyter notebooks 
#x.append to add wtv u want
#tbh feel like the other way is faster?


In [31]:
x=[1]
x.append(2,3,4)
x

#oops oh well

TypeError: list.append() takes exactly one argument (3 given)

## 2 Some loose ends

### 2.1 Tuples

In [35]:
a=(3,4,5,6,7,8,9,10,11,12,13,14,15,16)

#random tuple
#tuples, lists and arrays all start with index 0

print(a[5]) 

8


In [14]:
#typing without print works too 

a=(3,4,5,6,7,8,9,10,11,12,13,14,15,16)

#random tuple
#tuples, lists and arrays all start with index 0

a[5]

8

In [36]:
#just checking 

a=(3,4,5,6,7,8,9,10,11,12,13,14,15,16)

print(a[5]+[1])

#cannot change a tuple!

TypeError: unsupported operand type(s) for +: 'int' and 'list'

### 2.2 Be VERY careful when copying

In [ ]:
#dont casually equate!
#stack .copy() function at the end 

x=[1, 2, 3]
y=x.copy()
z=x.copy()

In [38]:
#just to be sure

x=[1, 2, 3]
y==x           

print (y[0])

#aights

NameError: name 'y' is not defined

## Exercise 1 :  Total recall?

1. Subsetting is the general term for referencing terms within a list or array
2. Indexing is calling on a specific element within a list or array 
3. Slicing is like indexing except you're calling on a range of elements within a list or array 
4. Masking is calling upon certain elements within the list or array which fulfil a preset condition 

## Exercise 2 :  Show me the ‘odd’ letters

In [52]:
#subsetting all the first elements
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

np_array_2d[0:8,0]
#or
np_array_2d[:,0]


array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U11')

In [15]:
#astype
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])


np_array_ints = np_array_2d[:,0].astype(int)

print(np_array_ints)

#print(np_array_2d[:,0]) doesn't work because the output will be standardised to str
#numpy arrays can only standardise to one type and since int is easier to convert to str all will become str

[ 1  3  2  4  5  7  6  8 10  9]


In [7]:
#remainder after dividing by 2
np_array_ints = np_array_2d[:,0].astype(int)

np_array_div2 =  np_array_2d[:,0].astype(int) % 2

print(np_array_div2)

[1 1 0 0 1 1 0 0 0 1]


In [19]:
#creating mask 
np_array_ints = np_array_2d[:,0].astype(int)

np_array_div2 =  np_array_2d[:,0].astype(int) % 2

mask = np_array_div2 == 1

print(mask)


[ True  True False False  True  True False False False  True]


In [21]:
#extract odd numbers

#just learnt from hari that mask only prints true values 

np_array_2d[mask,1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')

In [17]:
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])


np_array_ints = np_array_2d[:,0].astype(int)

#remainder after dividing by 2
np_array_ints = np_array_2d[:,0].astype(int)

np_array_div2 =  np_array_2d[:,0].astype(int) % 2 == 1

np_array_ints[np_array_div2,1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed